INSERT INTO USERS (ID, USERNAME, PASSWORD, ROL, ENABLED) VALUES (1, 'admin', '$2a$10$8X2uNE1GGDxIi/YPtU3FPOXwis1CR6TUgBvEUm5DK3fPahsmGWi1C', 0, true);
INSERT INTO USERS (ID, USERNAME, PASSWORD, ROL, ENABLED) VALUES (2, 'amanca', '$2a$10$8X2uNE1GGDxIi/YPtU3FPOXwis1CR6TUgBvEUm5DK3fPahsmGWi1C', 0, true);
INSERT INTO USERS (ID, USERNAME, PASSWORD, ROL, ENABLED) VALUES (3, 'flock', '$2a$10$8X2uNE1GGDxIi/YPtU3FPOXwis1CR6TUgBvEUm5DK3fPahsmGWi1C', 1, true);
INSERT INTO USERS (ID, USERNAME, PASSWORD, ROL, ENABLED) VALUES (4, 'simpleuser', '$2a$10$8X2uNE1GGDxIi/YPtU3FPOXwis1CR6TUgBvEUm5DK3fPahsmGWi1C', 2, true);
